name: SaLE
main: main.java.me.avankziar.sale.spigot.SaLE
version: 1
author: Avankziar
api-version: 1.19
description: A SignShop Plugin
depend: [InterfaceHub]
softdepend: [Vault,WorldGuard]
website: https://www.spigotmc.org/resources/shop-a-lot-extra.106371/