package me.avankziar.vss.spigot.gui.objects;

public enum GuiType
{
	ADMINISTRATION,
	NUMPAD_BUY,
	NUMPAD_SELL,
	NUMPAD_ACCOUNT,
	NUMPAD_POSSIBLE_BUY,
	NUMPAD_POSSIBLE_SELL,
	NUMPAD_DISCOUNT_START,
	NUMPAD_DISCOUNT_END,
	NUMPAD_DISCOUNT_HOUR,
	NUMPAD_DISCOUNT_BUY,
	NUMPAD_DISCOUNT_SELL,
	NUMPAD_DISCOUNT_POSSIBLE_BUY,
	NUMPAD_DISCOUNT_POSSIBLE_SELL,
	KEYBOARD_BLACKLIST,
	KEYBOARD_WHITELIST,
	KEYBOARD_MEMBER,
	KEYBOARD_CUSTOM,
	KEYBOARD_SIGNSHOPNAME,
	SHOP,
	ITEM_INPUT,
	SEARCH_BUY,
	SEARCH_SELL,
	SUBSCIBED
}
