package me.avankziar.vss.spigot.gui.objects;

public enum GuiType
{
	ADMINISTRATION,
	NUMPAD_ACCOUNT,
	KEYBOARD_WHITELIST,
	KEYBOARD_MEMBER,
	KEYBOARD_SIGNSTORAGENAME,
	ITEM_INPUT,
	SEARCH_BUY,
	SEARCH_SELL,
	SUBSCIBED
}
